sonar.projectKey=ksurahan-source_hiob-compositions
sonar.organization=ksurahan-source
sonar.projectName=hiob-compositions
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/__tests__/**,src/__fixtures__/**,src/**/*.{test,spec}.{ts,tsx}
sonar.exclusions=src/**/__tests__/**,src/__fixtures__/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
